---
- name: Configure web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Create a test file
      copy:
        content: "Hello from Ansible!\n"
        dest: /home/mightyed/ansible_test.txt
